### ISSUE TITLE
Typo in IndicatorLights_ReStock.cfg

### ISSUE THREAD

**Issue by Beetlecat** [KSPSnark/IndicatorLightsCommunityExtensions#5]
Typo when defining the storage unit; it's missing a "-1" at the end of the name. It should look like here in IndicatorLights_ReStock.cfg (at line #857). Is causing the box to be invisible (except for the light bars themselves):

//Science Box
@PART[ScienceBox]:AFTER[ReStock]:NEEDS[IndicatorLights]
{
	-MODEL,* {}
	MODEL
	{
		model = ReStock/Assets/Science/restock-sciencebox-radial-1
	}

**Comment by KSPSnark** [comment]
Addressed in the release of ILCE 1.6.1.  Thanks!
